language: node_js
node_js:
  - 9
branches:
  except:
    - /^no-ci.*$/
before_install:
  - export TZ=Asia/Singapore
script:
  - npm run format:ci
  - npm run build
  - npm run tslint
  - npm test
  - npm run test-coveralls
