language: node_js
node_js:
  - 10
branches:
  except:
    - /^no-ci.*$/
before_install:
  - export TZ=Asia/Singapore
  - export NODE_OPTIONS=--max_old_space_size=8192
script:
  - yarn run format:ci
  - yarn run build
  - yarn run tslint
  - yarn run test-coveralls
